[package]
name = "rixty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blink-alloc = "0.3.1"
rclite = "0.2.4"
mimalloc = { version = "*", default-features = false }